### ISSUE TITLE
Remove "creators" paragraph on FAQ for launch

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#16]
Comment out the following in the branch that will go live on Monday:

Creators
Looking for access to the Creator Beta? DM us! Want to be part of our creator community and get a free shoot? Apply to Get Trashed 🙌

**Comment by hannahdonovan** [comment]
@lujainibrahim did this get done? Cleaning up these tickets post launch :)

**Comment by lujainibrahim** [comment]
Yes. Fixed this! Will close it now
