### ISSUE TITLE
Better web player previews

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#191]
As a user, you should be able to send someone a video (on social media or SMS) and they can see a nice web preview, and then tap on that video to go directly to the video in the channel.

* if you have the app, it should take you directly there
* if you don't have the app you should be prompted to download it

------

Users want to share Trash videos, and promote Trash, to potential users outside the app. 
Need a way to show those videos off. 

Example Case:
Slack from Han:
I’m having a lot of fun w the new share / sending vids related to things I did w friends directly after I post to trash / getting their reactions.
I want this to include a link to the video on my profile tho like a deep link not just the vid... (later!)
![image.png](https://images.zenhubusercontent.com/5cdf2102ed322539edd0446d/93317a3b-8b39-41e1-a8c6-9492ce9541a9)

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

@hannahdonovan and @TrevorBaum I need a little input about if we want a different look on these pages for MLP, do we want a control for paging or infinite scroll, etc. Here is what there is right now

Play a single post
https://trash.app/player.html?id=4ba73b4f-2948-4843-9272-3089f1fb3b14

Play all videos in a channel (now only shows 10)
https://trash.app/channel.html?id=a5859caa-d4c9-40b8-95dd-fb7683b2ce1a
https://trash.app/channel.html?id=08a8ed27-3aa2-401d-af07-e849e3d8b0d3

Play all videos in a user's profile
https://trash.app/profile.html?id=fc0134d0-669e-45f7-bca4-0bb7305956f2
https://trash.app/profile.html?id=68625a28-5c40-4de2-bc58-d0c7fcd7a10c

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

@BrandonZacharie this issue actually has two parts - 1) web players, 2) deep links. Could you investigate a deep link for a post into the profile channel video paged up the the correct location to show the desired video? Then a visiting user could scroll back and forth and see other videos in the sending user's profile channel.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

@BrandonZacharie I tried to make the player.html page have a video as the preview in an SMS or similar sort of message, but I didn't figure it out. Just jotting down what I tried here. 

When the player.html page get the signed url for the video, the `fetch()` callback in the <script> on that page should update the <meta property="og:video" ...> in the <head>. This isn't happening though, and even if it happened I don't know how to easily test that it's working with out texting a like to people...
```
$("head").append('<meta property="og:video" content="'+video.src+'">');
```

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

The webplayer part of this is finished. Please review how it looks @TrevorBaum 

The preview link for the webplayer does not yet behave differently for if you are on ios (deep link) or not (web link)

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

@hannahdonovan and @TrevorBaum I need a little input about if we want a different look on these pages for MLP, do we want a control for paging or infinite scroll, etc. Here is what there is right now

Play a single post
https://trash.app/player.html?id=4ba73b4f-2948-4843-9272-3089f1fb3b14

Play all videos in a channel (now only shows 10)
https://trash.app/channel.html?id=a5859caa-d4c9-40b8-95dd-fb7683b2ce1a
https://trash.app/channel.html?id=08a8ed27-3aa2-401d-af07-e849e3d8b0d3

Play all videos in a user's profile
https://trash.app/profile.html?id=fc0134d0-669e-45f7-bca4-0bb7305956f2
https://trash.app/profile.html?id=68625a28-5c40-4de2-bc58-d0c7fcd7a10c

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

@BrandonZacharie this issue actually has two parts - 1) web players, 2) deep links. Could you investigate a deep link for a post into the profile channel video paged up the the correct location to show the desired video? Then a visiting user could scroll back and forth and see other videos in the sending user's profile channel.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

@BrandonZacharie I tried to make the player.html page have a video as the preview in an SMS or similar sort of message, but I didn't figure it out. Just jotting down what I tried here. 

When the player.html page get the signed url for the video, the `fetch()` callback in the <script> on that page should update the <meta property="og:video" ...> in the <head>. This isn't happening though, and even if it happened I don't know how to easily test that it's working with out texting a like to people...
```
$("head").append('<meta property="og:video" content="'+video.src+'">');
```

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

The webplayer part of this is finished. Please review how it looks @TrevorBaum 

The preview link for the webplayer does not yet behave differently for if you are on ios (deep link) or not (web link)

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/285
