### ISSUE TITLE
Testing firebase notifications

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#192]
As a company, we would like to have a way for a non-technical team member to send a handful of test notifications (just like Mailchimp) so we can send a few test notifications before pushing the notification out to our whole userbase.

https://console.firebase.google.com/u/0/project/benny-prod/notification/compose

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

@karina4now is this still a problem?

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

@karina4now is this still a problem?

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/286
