### ISSUE TITLE
Push notifications to logged out users

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#194]
As a user, I still want to be notified of feels on my posts even if I've been logged out somehow. 

As a community manager, I want to bring people back to the app with an exciting message even if they've logged out. 

I don't understand why Benny can't send push notifications to logged out users, because FCM uses a server-device combination token not a server-user token. Benny should send notifications to the last known device tokens (or all available device tokens). (https://stackoverflow.com/questions/56969940/sending-firebase-push-notifications-to-logged-in-users-only, https://stackoverflow.com/questions/53548398/how-can-i-send-notifications-when-a-user-is-logged-out)

I think Benny may be deleting device tokens from the device_registration table at some point, possibly when the user is logged out. This should be changed.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

New idea for how to fix this: make all new Trash users have anonymous firebase accounts associated with their device ids. This should make it possible to notify anyone, even if they haven't logged in for the first time. Also checkin with @drewolbrich about notifications that could be in-app notifications and not use firebase/

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

New idea for how to fix this: make all new Trash users have anonymous firebase accounts associated with their device ids. This should make it possible to notify anyone, even if they haven't logged in for the first time. Also checkin with @drewolbrich about notifications that could be in-app notifications and not use firebase/

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/292
