### ISSUE TITLE
Watch-back notification

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#199]
As a company, we want to suggest to users that they watch list someone back when they get watch listed

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

TrevorBaum commented in Github:

Copy ideas for notifications:
"Username added you to their My Angels channel!"
"Username just added you on TRASH! Add them back 😇"

**Comment by chihyuC** [comment]
dup
