### ISSUE TITLE
Fix web player preview metadata

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#203]
Currently the web player preview links are formatted like:

> [Username] on TRASH
> 0d ago - 60 views

Please implement the following changes:

- "Views" should be updated to say "plays"
- The order of the timestamp and play count should be swapped
- The "-" hyphen should be replaced by "•"
- Formatting of the timestamp should not say 0d, but should follow the conventions in the iOS app, ex: "5m ago"

It should look like this:

> [Username] on TRASH
> 60 plays • 5m ago

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/364
