### ISSUE TITLE
Published tracks not showing up in app

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#215]
During an onboarding call with artist Z Renzo, we went through all of the normal steps for uploading a track. He updated his profile setting his artist and user names and saved the changes. He checked off permissions, updates song info, and then uploaded his track "Vision" which was a .wav file. The processing took a while but the track uploaded and is playable in the database. He published it but it is not visible in the app even after closing/reloading.

I had him re-upload the track as an mp3. So he created a new record with the same process but with an mp3 file instead and published it, but it still isn't showing up in the app.

I am able to see & play both the .wav and mp3 versions in the staff console but not in the app. All of the info about the track is still saved.

***Expected outcome:*** When a track is published on TRASH for Artists it is immediately available in the app under the artists name.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

hannahdonovan commented in Github:

Notes from planning: maybe this is part of the lambda process? This is a Gen or SB question…

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/500
