### ISSUE TITLE
Notify if sampled

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#222]
As a user, I want to know when someone makes a video with one of my clips via a push notification that deep links me to their post.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

hannahdonovan commented in Github:

FYI @genp for when you are looking into our Firebase notifications, this is another type we should be able to send…

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/408
