### ISSUE TITLE
Error 332, -11828 unrecogized soundtrack file format

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#231]
This error appears frequently in the development build of the app, about once per day of regular use:
[file id="ef998e80-3266-46a6-b5a3-b93b461080b1"]

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

This is caused by TFA uploads with .aiff format

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

hannahdonovan commented in Github:

Notes from planning: we're going to limit artists to mp3 for now, come back to this later to re-investigate.

Change the copy on the website (not going to change any underlying code), just tell people to use mp3 for now. This is also better for upload times bc .wav really big

**Comment by karina4now** [comment]
> Arkadiusz Pęcherz commented in Jira:

Szymon PółtorakIt seems that you went too far with restrictions😃I'm unable to upload an .mp3 file due to


```
Unsupported type: audio/mpeg
```

[file id="8ae7a96b-3120-4cec-b0bf-260262df0474"]

**Comment by karina4now** [comment]
> Wojciech Krysiak commented in Jira:

so eventually we will go with:


```
'audio/mp3',
'audio/mpeg',
'audio/m4a'
```

**Comment by karina4now** [comment]
> Arkadiusz Pęcherz commented in Jira:

Wojciech Krysiakjust to be sure- as you said that 'audio/m4a' is allowed, but I checked that these two files don't work. Please address if it's a blocker or not
[file id="a3adbe14-f085-4119-bc1b-0cca77021d4a"][file id="73416265-920a-42c0-8adc-d82281ef0c4a"]

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/489
