### ISSUE TITLE
Broken pagination in TFA panel - allows to go to empty pages

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#232]
login to TFA as an admin

open Tracks

notice the number of tracks

use the navigation to go to the page where the last tracks should be displayed (in this case it should be 6th page for 514 records - 100 tracks per page)

go to another page

**Actual result:**The pagination exceeds total pages value. It's possible to navigate to empty pages
[file id="d07f31f0-39f3-40ae-be5a-36c03b91486a"]
**Expected result:**The last page possible to navigate using the pagination buttons should move the user to the last page that contains records. It should not be possible to go to other pages - they should not be displayed in the navigation bar

**Comment by karina4now** [comment]
> Wojciech Krysiak commented in Jira:

Arkadiusz PęcherzI deploy this fix to production (is embded to newest admin-bro release)

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/488
