### ISSUE TITLE
The Artist Upload web site should strip leading and trailing whitespace from artist names (like ” Philthy” on production which has a leading space character) and the contents of every other text field

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#233]
Description:  The Artist Upload web site should strip leading and trailing whitespace from artist names (like ” Philthy” on production which has a leading space character) and the contents of every other text field

Reported in Slack by: drew.olbrich
Reported: 

Link to Slack Thread:
https://thetrashapp.slack.com/archives/CHVNUEYN6/p1584021368001100

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

I manually fixed the examples you mentioned for now.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

I've modified the client to strip leading and trailing whitespace for soundtrack collection titles when they're displayed, so it least they don't look lopsided when they're displayed, but this doesn't fix the actual problem.

In general, it's a best practice to strip leading and trailing whitespace from all user input, for example in JavaScript like this: https://www.w3schools.com/jsref/jsref_trim_string.asp

For example, consider the case where a user is trying to sign in and they enter their email address and it looks correct to them, but they accidentally entered a space before their email address, and consequently they can't sign in because strictly speaking, they didn't enter their exact email address so the strings don't match.

This seems implausible but this is what Philthy did.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

hannahdonovan commented in Github:

Notes from planning: fixed this on the front end but that doesn't fix that this is still an issue on the backend which is not good either…

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/487
