### ISSUE TITLE
Ability to publish tracks privately

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#236]
Artists want the ability to publish tracks privately so that other users cannot make videos with their music.

They need to be able to toggle this on/off from the TFA portal.

They need a way to access these tracks in the app.

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/421
