### ISSUE TITLE
Add "Sign in with Apple" to web login page

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#237]
As a user, I want to have "Sign in with Apple" on the web as well, so that I can log in with the same account I used on the app.

Currently, there's no way for a user to log in with the same account on the web, if the user created an account in the app with AppleID. I tried using the email Apple generated and went through the "Sign in with Email" flow but it ended up creating a new account for me.

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/425
