### ISSUE TITLE
Ability to do user impersonation (god mode)

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#242]
As a staff member handling user services, I will sometimes need to responsibly log in as another user who is having an issue so I can help debug the problem.

This requires investigation about what the best practices are around security, a quick look online [turned up this thread](https://www.indiehackers.com/post/how-do-you-implement-god-mode-in-your-app-7b3fcb19d4) with a lot of the questions we will need to ask.

**Scenarios:**
* A staff member needs to log in as an artist to do some white glove support for them, ie. upload vid
* A staff member needs to log in as a user to debug an issue they're experiencing ie. login issue

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/430
