### ISSUE TITLE
Ability to pin videos to the front of the channel

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#285]
As a company, we want to be able to moderate content by pinning top videos to the front of the channel. We are currently restricted to either choosing chronological or reverse chronological for the order of the videos in the channel, which limits us from highlighting certain content. 

Acceptance criteria:
* staff function enabling us to pin a video to the front of the channel
* staff function enabling us to unpin a video from a channel
* there should be no maximum number of videos that can be pinned

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/trash-inc.github.io/291
