### ISSUE TITLE
Ability to pin/unpin posts

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#291]
As a staff member I want to be able to pin multiple (unlimited) posts in channels and determine their order so that I can ensure the initial viewing experience is great.

As a company, we'll need some kind of UI in the admin panel to be able to:
* find a post
* pin the post to a channel
* choose the order (first, fourth etc.)
* see all the pinned posts in a channel and unpin them

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

This is currently a Grizzy ticket but I think it should be Benny.

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/742
