### ISSUE TITLE
Expose all user information (including user_profile table) to Admin Panel under "Trash User" tab

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#300]
As a company, I want to search a user by username and view all information about a user.

Currently on the Admin Panel, we're only displaying user information from the `trash_user` table, which doesn't include all the `username` related information. This makes searching for a user harder so we'd like to include more user information.

**Acceptance Criteria**
- Add a `username` column which displays information inside `UserProfile.username` to the chart
- Add ability to search by `username`
- In the Show page, display all user information from both `trash_user` and `user_profile` table

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/658
