### ISSUE TITLE
Error when searching for a user by uuid on Admin Panel

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#301]
***Steps***

Log in to Admin Panel as a staff user

Click on "Trash User"

Copy any id from the id column

Go to Filter page

Paste the copied id

Click on Apply Changes

***Expected behavior***If a matching user is found, display it. Otherwise, show no records.

***Current behavior***An error is thrown and the page is in loading state forever.

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/659
