### ISSUE TITLE
As an artist I want to be notified when my track is live

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#302]
**Business value**

Notify artists when tracks go live. (Ie. When a staff member hits publish)

**Acceptance criteria**

Notification and email via our backed

mandatory email, as discussed with SBs we'll remove phone for now

send one email saying:

your tracks are in the queue

go download the app (after they hit submit)

here is a copy of the terms to send to your writing partner if you need

your tracks are in the queue

go download the app (after they hit submit)

here is a copy of the terms to send to your writing partner if you need

**Copy for the autosend emails**https://docs.google.com/document/u/3/d/1PX2Ryps1__z7tYhBADnyZh8GPp98C_Woh1_r3DzN56M/edit#

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

hannahdonovan commented in Github:

As a company, we need to communicate with TFA artists to send them updates, notifications and documents.

1. mandatory email, as discussed with SBs we'll remove phone for now
2. send one email saying:
- your tracks are in the queue
- go download the app (after they hit submit)
- here is a copy of the terms to send to your writing partner if you need
3. second email saying that your tracks are in the app now
4. NTH - put all artists emails on a Mailchimp list so we can send them marcom emails later (potentially using Mandrill as Wojciech suggests

@ezra-latina can you please review asap and lmk if this sounds about right? I'm pretty concerned about them making the jump from web to app, and wondering if we need a final modal there to tell them what is next. Can you think of all the places artists would get lost if you weren't there to hold their hand and bring these up today in our TFA meet?

**Comment by karina4now** [comment]
> Piotr Brzęczek commented in Jira:

Issue split into:

https://kmpgroup.atlassian.net/browse/TRSH-297#icft=TRSH-297

Notify admin when tracks go to review

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

ezra-latina commented in Github:

Copy for the autosend emails [https://docs.google.com/document/u/3/d/1PX2Ryps1__z7tYhBADnyZh8GPp98C_Woh1_r3DzN56M/edit#](url)

**Comment by karina4now** [comment]
> Ezra Latina commented in Jira:

Here is the link to theMailChimp templatefor the track acceptance email.

The audience is called TRASH for Artists and is tagged with #TFA.

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/752
