### ISSUE TITLE
As a user, I want the video to start playing once it finishes loading

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#314]
**Business value**

All videos should autoplay in the web player

**Current behavior**

Single video player: After the page loads, I need to click on play button to start playing the video

Channel player: After the page loads, and every time I click on prev/next buttons, I need to click on play button to start playing the video

**Expected behavior**

The video should just auto-play in scenarios described above.

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/703
