### ISSUE TITLE
Artist upload wireflows

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#32]
Initial wireflows for legal sign off Tue 9/24 to go into production. Will likely be a web UI so filing here.

**Comment by ezra-latina** [comment]
The upload flow:
* user makes an account with TRASH
* user gets to portal (how? link in app?)
* user is presented with on-boarding page with info about what they are submitting to
* user starts upload process through portal
* Are you okay with letting other TRASH users make videos with your track too?
* Who wrote this song? 
* Who performed on this song? 
* Do you have permission to upload this song? 
* Is this song or any contributor part of an agreement with a label and/or publisher? 
* What is the track info? (Title, artist name, writer name)


Other Parameters
* Do a random audit? Maybe once a month to pick an artist and check their answers line up accurately 
* Need an on-boarding page - By signing up, here is what trash is about
* Manat to review our terms of service to make sure we are covered for music
* Not fully open to all - control the flow and gather feedback and make functionality clean then open it up and

**Comment by ezra-latina** [comment]
@genp here are the notes from legal about how the flow should go
