### ISSUE TITLE
New web player takes a long time to refresh and load

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#320]
**Steps**

Open the player link on mobile

**Expected behavior**

The user sees an en enlarged and cropped preview, and after waiting for a long time it finally loads and resizes properly

**Current behavior**

The video begins playing sooner. Also, the player should resize properly on first load.
[file id="fd6c5de6-bccf-4919-b97f-cf27d6616508"]

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/692
