### ISSUE TITLE
Sound icon doesn't scale/stay relatively to the player when resizing

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#321]
**Steps**

Load the new player in browser

Drag to resize it

**Expected behavior**

The sound icon stay relative to the player (or inside the player)

**Current behavior**

The sound icon is positioned far above the player
[file id="f1334c17-beaf-4370-b9e5-60294eca3513"]

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

chihyuC commented in Github:

Same problem for next/prev buttons.

**Comment by karina4now** [comment]
> Arkadiusz Pęcherz commented in Jira:

Rafał Dzięgielewskiicons are still not fully responsive
[file id="a63d387d-9f28-4fa2-8d4f-e270e766a654"]

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

chihyuC commented in Github:

Same problem for next/prev buttons.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Arkadiusz Pęcherz commented in Jira:

Rafał Dzięgielewskiicons are still not fully responsive
[file id="a63d387d-9f28-4fa2-8d4f-e270e766a654"]

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

chihyuC commented in Github:

Same problem for next/prev buttons.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Arkadiusz Pęcherz commented in Jira:

Rafał Dzięgielewskiicons are still not fully responsive
[file id="a63d387d-9f28-4fa2-8d4f-e270e766a654"]

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/688
