### ISSUE TITLE
Forced to click Join or Sign In twice to enter

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#323]
**Expected Behavior**

click join or sign in

select google account

if TRASH acct already exists - take me directly into the site

if no TRASH acct exists - take me to sign up

**Current Behavior**

I click join or Sign in

select google account for existing TRASH acct

takes me back to landing page

I click join or sign in again and am taken to homepage

**Comment by karina4now** [comment]
> Rafał Dzięgielewski commented in Jira:

I used designs below as a reference when making style changes.
[file id="a0a9195a-6895-4613-b2a5-e9b2e3a1599a"][file id="b5630852-9770-4086-8411-78d30e8284c2"]

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Rafał Dzięgielewski commented in Jira:

I used designs below as a reference when making style changes.
[file id="a0a9195a-6895-4613-b2a5-e9b2e3a1599a"][file id="b5630852-9770-4086-8411-78d30e8284c2"]

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Rafał Dzięgielewski commented in Jira:

I used designs below as a reference when making style changes.
[file id="a0a9195a-6895-4613-b2a5-e9b2e3a1599a"][file id="b5630852-9770-4086-8411-78d30e8284c2"]

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/691
