### ISSUE TITLE
Nav issue: terms should open in new tab

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#324]
In the track upload flow, in step 3 if a user clicks on the Terms to review them before accepting they cannot go directly back to the Upload page.
[file id="e81dcf08-d027-4aaa-9bb8-545a9e6cea8a"]
**Expected Outcome**

I click on Terms and Conditions

I navigate to the terms page via new tab

I can close tab and go back to step 3 of upload flow

**Current Outcome**

I click on Terms and Conditions

I navigate to the terms page

when I click the back arrow I am brought to the landing page (with the big Join button)

I have to sign in again and edit my track to get back to where I was

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

ezra-latina commented in Github:

created benny version

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

ezra-latina commented in Github:

can we set it to open in a new tab instead?

**Comment by karina4now** [comment]
> Wojciech Krysiak commented in Jira:

Arkadiusz Pęcherzits on production (Friday deploy) but I would like that you will test it

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Grizzy/issues/1597
