### ISSUE TITLE
Forced to click Join twice to enter

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#325]
Expected Behavior: 
- click join
- select google account
- if TRASH acct already exists - take me directly into the site
- if no TRASH acct exists - take me to sign up

Current Behavior:
- click join
- select google account for existing TRASH acct
- takes me back to landing page
- i click join again and am taken to homepage

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

Is this ticket for the app or for the web site?

**Comment by karina4now** [comment]
> Piotr Brzęczek commented in Jira:

I believe it is related to login page of TFA

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

ezra-latina commented in Github:

the website

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

ezra-latina commented in Github:

created new issue in benny

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/737
