### ISSUE TITLE
Add ability to have channels per style

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#363]
As a user, I want to be able to see all the videos made with a particular style.

In the future version of the publishing styles feature, we'd like to show users a list of related videos so they can get inspiration before making their own video, after tapping on the style button of a certain video.

Currently, we don't have any channel for a style, nor do we have an easy way to retrieve a list of videos related to a certain style. Any style related information exists on backend in the `metadata` field of a video, in JSON format, which is not limited to style only and could change overtime by the use of app. When we implement this, consider adding/moving the necessary style information out to a more permanent column/table.

Acceptance criteria:
- Ability to quickly retrieve a list of videos made of a certain style
- Extend the existing channel query or a new style channel query that returns the list of videos given a `styleId`
- Supporting adding new styles without code change on backend

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

Before embarking on a schema migration, let's try to achieve the user-facing objectives with the `metadata::jsonb` field we are prototyping with. Here is sql for accomplishing each of the above tasks at the psql terminal. We can turn these sql commands into graphql queries (either with sequelize or literal sql, example at the bottom). We could add database triggers for organizing new posts into style channels when they are uploaded. Let's try these quick and simple options first, and only upgrade when the feature becomes popular and we suffer performance issues.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

If we want to have a style channel, but not show it on the `Discover` screen in the app, make the channel type 'USER'.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

Git grep this repo for TRIGGER to see some migration examples where a DB trigger was added. I would write a migration to add all the style channels you want (use the `literal` option from sequelize), and add a DB trigger in the migration the way previous developers have. 

Test the trigger on dev or stage first. This trigger will be a bit more complicated than what's in our migration history. I think it will be something like this, but not exactly this because I know this isn't exactly right:
```
trash_stage=> CREATE OR REPLACE FUNCTION curate_to_style_channel_procedure () RETURNS TRIGGER AS $$                                                                                            
BEGIN
     IF NEW.post_id in  (select id from post where metadata::text like '%"styleId": "<style uuid>"%') THEN
       INSERT INTO
         channel_post (channel_id, post_id, created_at, updated_at)
         VALUES ('<style channel_id>', NEW.id, now(), now());
     END IF;
     RETURN NEW;
  END;
$$
LANGUAGE plpgsql;

trash_stage=> CREATE TRIGGER curate_to_style_channel_trigger
      AFTER INSERT
      ON post
      FOR EACH ROW
      EXECUTE PROCEDURE curate_to_style_channel_procedure ();
```

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

@genp This strategy of presenting styles as channels is fantastic, because on the screen that displays video thumbnail images for a list of videos associated with a style, it should allow us to use the existing paging mechanism to display arbitrarily long lists of video thumbnail images in a collection view using our existing `channelForward` query without having to write more paging support, and then once we have that implemented, we can use that same collection view on a future improved profile screen that displays video thumbnail images in the same format, without additional back end work.

@genp Do you know if SB will be supplying static thumbnail images for each video? We'll really need that for this feature. We can't display two dozen live video thumbnails on the screen at once and spin them all up as the user is scrolling down the screen. It will be a disaster and the user will only see gray boxes even if everything is working smoothly. Displaying live videos barely works on our discover screen, which only shows 6 videos at a time. There's a reason that apps like TikTok show either static thumbnails or extremely short animated GIFs in interfaces like this.
^^^ @chihyuC

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

great it looks like there's something at https://docs.google.com/spreadsheets/d/1CNd-7-iBHAMzNEFdtRwH5CUs4xBKM8cj3cxzZK6mHFY/edit?ts=5e8c0a7a#gid=0

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

however ... if these are on the order of 720x1280 then they are too large
@chihyu we should probably ask SB to provide new sizes for static thumbnails once we figure out what size they should be, once the UX design is nailed down

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

also actual GIFs won't work for these because if they're 8 bits per pixel with ordered dithering like the ones we were including in links, that will look awful

@genp Do you know know why our existing GIFs used ordered dithering (and a fixed evenly distributed web-safe palette, I am guessing) instead of error diffusion dithering (and an adaptive color palette)? Error diffusion dithering won't look quite as overly pixelated. We should try this if it's something that FFMPEG already supports and the cost of trying it is low.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

The SBs set up a lambda function to make a half dozen small thumbnail images of different aspect ratios including square. @wojtek-krysiak could you point @drewolbrich to how to view these thumbnail options by aws cli or some convenient method?

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

Before embarking on a schema migration, let's try to achieve the user-facing objectives with the `metadata::jsonb` field we are prototyping with. Here is sql for accomplishing each of the above tasks at the psql terminal. We can turn these sql commands into graphql queries (either with sequelize or literal sql, example at the bottom). We could add database triggers for organizing new posts into style channels when they are uploaded. Let's try these quick and simple options first, and only upgrade when the feature becomes popular and we suffer performance issues. 

How to retrieve all posts with a specific style (here it is `Recap`):
```
trash_stage=> select id from post where metadata::text like '%"styleId": "e9252df4-29eb-4108-b3a4-fc8def64a68d"%';
                  id
--------------------------------------
 35a81fa4-927b-4e08-bcd6-4a329c0a5975
 d458a18a-ace4-4cc6-97b8-419df96c7fb2
 5f6f5d28-9118-4644-ba2f-fd9354eaf549
 8b10d48a-7e2b-4197-a21c-1b7761d97685
...
```

Make a channel for a style and and add all the videos with that style (this is what could be a DB trigger on post upload): 
```
trash_stage=> insert into channel values (default, 'Recap', 0, 'GROUP', default, null, now(), now(), false, -20, null);

trash_stage=> select id from channel where name='Recap';
                  id
--------------------------------------
 84d93a5f-2743-4b11-a2af-4da12d17974f
(1 row)
```

Insert all the posts with that style into the channel by creating entries in the `channel_post` join table:
```
trash_stage=> insert into channel_post (channel_id, post_id, created_at, updated_at) 
select '84d93a5f-2743-4b11-a2af-4da12d17974f', post_id, now(), now() from (select id as post_id from post where metadata::text like '%"styleId": "e9252df4-29eb-4108-b3a4-fc8def64a68d"%') as style_posts;

trash_stage=> insert into channel_post (channel_id, post_id, created_at, updated_at) 
select '<style channel_id>', post_id, now(), now() from (select id as post_id from post where metadata::text like '%"styleId": "<style uuid>"%') as style_posts;
```

Then the `Recap` channel can be retrieved using its `channel_id` from the regular channel query.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

If we want to have a style channel, but not show it on the `Discover` screen in the app, make the channel type 'USER'.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

Git grep this repo for TRIGGER to see some migration examples where a DB trigger was added. I would write a migration to add all the style channels you want (use the `literal` option from sequelize), and add a DB trigger in the migration the way previous developers have. 

Test the trigger on dev or stage first. This is the correct trigger. It is currently updating the 'Recap' channel on staging:
```
CREATE OR REPLACE FUNCTION curate_to_style_channel_procedure () RETURNS TRIGGER AS $$                                                                                            
BEGIN
     IF NEW.channel_id = '<The OG channel id, or FIRST 1K in Channel>' and NEW.post_id in (select id from post where metadata::text like '%"styleId": "<style uuid>"%') THEN
       INSERT INTO
         channel_post (channel_id, post_id, created_at, updated_at, type, user_id, source_channel_id, deleted_at)
         VALUES ('<style channel id>', NEW.post_id, NEW.created_at, NEW.updated_at, null, null, '<The OG channel id, or FIRST 1K in Channel>', NEW.deleted_at);
     END IF;
     RETURN NEW;
  END;
$$
LANGUAGE plpgsql;



CREATE OR REPLACE FUNCTION curate_to_style_channel_procedure () RETURNS TRIGGER AS $$                                                                                            
BEGIN
     IF NEW.channel_id = 'a5859caa-d4c9-40b8-95dd-fb7683b2ce1a' and NEW.post_id in (select id from post where metadata::text like '%"styleId": "e9252df4-29eb-4108-b3a4-fc8def64a68d"%') THEN
       INSERT INTO
         channel_post (channel_id, post_id, created_at, updated_at, type, user_id, source_channel_id, deleted_at)
         VALUES ('84d93a5f-2743-4b11-a2af-4da12d17974f', NEW.post_id, NEW.created_at, NEW.updated_at, null, null, 'a5859caa-d4c9-40b8-95dd-fb7683b2ce1a', NEW.deleted_at);
     END IF;
     RETURN NEW;
  END;
$$
LANGUAGE plpgsql;


CREATE TRIGGER curate_to_style_channel_trigger
      AFTER INSERT
      ON channel_post
      FOR EACH ROW
      EXECUTE PROCEDURE curate_to_style_channel_procedure ();
```

For the migration script, you'll want a way to delete the trigger:
```
DROP TRIGGER curate_to_style_channel_trigger on channel_post;

DROP FUNCTION curate_to_style_channel_trigger;
```

To see all the triggers available in a db:
```
\dft
```

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

@genp This strategy of presenting styles as channels is fantastic, because on the screen that displays video thumbnail images for a list of videos associated with a style, it should allow us to use the existing paging mechanism to display arbitrarily long lists of video thumbnail images in a collection view using our existing `channelForward` query without having to write more paging support, and then once we have that implemented, we can use that same collection view on a future improved profile screen that displays video thumbnail images in the same format, without additional back end work.

@genp Do you know if SB will be supplying static thumbnail images for each video? We'll really need that for this feature. We can't display two dozen live video thumbnails on the screen at once and spin them all up as the user is scrolling down the screen. It will be a disaster and the user will only see gray boxes even if everything is working smoothly. Displaying live videos barely works on our discover screen, which only shows 6 videos at a time. There's a reason that apps like TikTok show either static thumbnails or extremely short animated GIFs in interfaces like this.
^^^ @chihyuC

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

great it looks like there's something at https://docs.google.com/spreadsheets/d/1CNd-7-iBHAMzNEFdtRwH5CUs4xBKM8cj3cxzZK6mHFY/edit?ts=5e8c0a7a#gid=0

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

however ... if these are on the order of 720x1280 then they are too large
@chihyu we should probably ask SB to provide new sizes for static thumbnails once we figure out what size they should be, once the UX design is nailed down

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

also actual GIFs won't work for these because if they're 8 bits per pixel with ordered dithering like the ones we were including in links, that will look awful

@genp Do you know know why our existing GIFs used ordered dithering (and a fixed evenly distributed web-safe palette, I am guessing) instead of error diffusion dithering (and an adaptive color palette)? Error diffusion dithering won't look quite as overly pixelated. We should try this if it's something that FFMPEG already supports and the cost of trying it is low.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

genp commented in Github:

The SBs set up a lambda function to make a half dozen small thumbnail images of different aspect ratios including square. @wojtek-krysiak could you point @drewolbrich to how to view these thumbnail options by aws cli or some convenient method? I think that the s3 urls or bucket/key pairs for all the thumbnails will be stored in the `variants` field of the `post` table, for when the client needs them. I don't think this lambda is running all the time yet, so recent posts don't have this info yet.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

genp commented in Github:

Before embarking on a schema migration, let's try to achieve the user-facing objectives with the `metadata::jsonb` field we are prototyping with. Here is sql for accomplishing each of the above tasks at the psql terminal. We can turn these sql commands into graphql queries (either with sequelize or literal sql, example at the bottom). We could add database triggers for organizing new posts into style channels when they are uploaded. Let's try these quick and simple options first, and only upgrade when the feature becomes popular and we suffer performance issues.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

genp commented in Github:

If we want to have a style channel, but not show it on the `Discover` screen in the app, make the channel type 'USER'.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

genp commented in Github:

Git grep this repo for TRIGGER to see some migration examples where a DB trigger was added. I would write a migration to add all the style channels you want (use the `literal` option from sequelize), and add a DB trigger in the migration the way previous developers have. 

Test the trigger on dev or stage first. This trigger will be a bit more complicated than what's in our migration history. I think it will be something like this, but not exactly this because I know this isn't exactly right:
```
trash_stage=> CREATE OR REPLACE FUNCTION curate_to_style_channel_procedure () RETURNS TRIGGER AS $$                                                                                            
BEGIN
     IF NEW.post_id in  (select id from post where metadata::text like '%"styleId": "<style uuid>"%') THEN
       INSERT INTO
         channel_post (channel_id, post_id, created_at, updated_at)
         VALUES ('<style channel_id>', NEW.id, now(), now());
     END IF;
     RETURN NEW;
  END;
$$
LANGUAGE plpgsql;

trash_stage=> CREATE TRIGGER curate_to_style_channel_trigger
      AFTER INSERT
      ON post
      FOR EACH ROW
      EXECUTE PROCEDURE curate_to_style_channel_procedure ();
```

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

@genp This strategy of presenting styles as channels is fantastic, because on the screen that displays video thumbnail images for a list of videos associated with a style, it should allow us to use the existing paging mechanism to display arbitrarily long lists of video thumbnail images in a collection view using our existing `channelForward` query without having to write more paging support, and then once we have that implemented, we can use that same collection view on a future improved profile screen that displays video thumbnail images in the same format, without additional back end work.

@genp Do you know if SB will be supplying static thumbnail images for each video? We'll really need that for this feature. We can't display two dozen live video thumbnails on the screen at once and spin them all up as the user is scrolling down the screen. It will be a disaster and the user will only see gray boxes even if everything is working smoothly. Displaying live videos barely works on our discover screen, which only shows 6 videos at a time. There's a reason that apps like TikTok show either static thumbnails or extremely short animated GIFs in interfaces like this.
^^^ @chihyuC

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

great it looks like there's something at https://docs.google.com/spreadsheets/d/1CNd-7-iBHAMzNEFdtRwH5CUs4xBKM8cj3cxzZK6mHFY/edit?ts=5e8c0a7a#gid=0

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

however ... if these are on the order of 720x1280 then they are too large
@chihyu we should probably ask SB to provide new sizes for static thumbnails once we figure out what size they should be, once the UX design is nailed down

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

drewolbrich commented in Github:

also actual GIFs won't work for these because if they're 8 bits per pixel with ordered dithering like the ones we were including in links, that will look awful

@genp Do you know know why our existing GIFs used ordered dithering (and a fixed evenly distributed web-safe palette, I am guessing) instead of error diffusion dithering (and an adaptive color palette)? Error diffusion dithering won't look quite as overly pixelated. We should try this if it's something that FFMPEG already supports and the cost of trying it is low.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

genp commented in Github:

The SBs set up a lambda function to make a half dozen small thumbnail images of different aspect ratios including square. @wojtek-krysiak could you point @drewolbrich to how to view these thumbnail options by aws cli or some convenient method?

**Comment by wojtek-krysiak** [comment]
@drewolbrich regarding thumbnails I restricted it to just 2 versions (one original and one with button overlay). They can be seen in the API under the `key_frame_urls` property. I did this restriction because I wanted to store previews ASAP so they can be taken by social platforms. But @genp is right - we can easily add whatever ratio (1x1 16x9 etc) we want.

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/664
