### ISSUE TITLE
The following buttons should be icons on the TFA site

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#364]
![Screen Shot 2020-05-14 at 2.23.55 PM.png](https://images.zenhubusercontent.com/5d488d57b57e59000137d4db/a30688de-ac0a-43b5-91b7-1521b0d5d7ca)

These currently operate as buttons, if you click them they bring you to the track upload flow.

They should operate as labels in simple text. 

![Screen Shot 2020-05-14 at 2.25.47 PM.png](https://images.zenhubusercontent.com/5d488d57b57e59000137d4db/9194178d-1109-4edd-b815-a1a1e5fa2e02)

While this does not operate as a button (it is not clickable), it lights up when you hover over it. It should also be a simple plain text label.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

hannahdonovan commented in Github:

These should all be true pill shapes.

Draft should be grey (as it is)
Pending should be white
Published should be purple: BD9FFF

![Screen Shot 2020-05-14 at 11.33.29.png](https://images.zenhubusercontent.com/5cba4ff1fec3b63424e0f7d8/a13f6995-ef6e-4f07-bc7d-034b1f0d9d48)

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/753
