### ISSUE TITLE
TFA Web Design Polish

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#366]
This is a rough list of things on the TFA site that need to be polished.

1. Sign in button is not obviously clickable. Needs to pop more.
![Screen Shot 2020-05-14 at 9.59.01 PM.png](https://images.zenhubusercontent.com/5d488d57b57e59000137d4db/6657f5d1-7894-4156-b53b-7ff245acce9e)

2. There are no hover states for the buttons - they stay the same when the mouse scrolls over them.

3. These types of messages are not obvious and are not cute. They are very easy to miss. 
 ![Screen Shot 2020-05-14 at 10.05.36 PM.png](https://images.zenhubusercontent.com/5d488d57b57e59000137d4db/6d2470f6-5097-4f2a-b6a1-385ef872675f)

4. FAQ should be in all CAPS
![Screen Shot 2020-05-14 at 10.07.46 PM.png](https://images.zenhubusercontent.com/5d488d57b57e59000137d4db/56bf2314-d8e1-4986-a32c-397eef7a34e2)

5. TFA logo needs to be updated in the top left corner
![Screen Shot 2020-05-14 at 10.08.24 PM.png](https://images.zenhubusercontent.com/5d488d57b57e59000137d4db/dc0d6b39-7ec0-4d98-bf32-dae9e7924f7e)

6. The timestamps next to tracks and videos look very crowded
![Screen Shot 2020-05-14 at 10.09.14 PM.png](https://images.zenhubusercontent.com/5d488d57b57e59000137d4db/31b017c9-267e-4dfb-9a52-6c1ba82de988)

7. The search filter screen is very confusing
![Screen Shot 2020-05-14 at 10.10.23 PM.png](https://images.zenhubusercontent.com/5d488d57b57e59000137d4db/ce9db27c-5f0d-4569-a3a4-2acf1111fa32)

8. Profile Display is kinda lame 
![Screen Shot 2020-05-14 at 10.12.33 PM.png](https://images.zenhubusercontent.com/5d488d57b57e59000137d4db/57d6a3e4-4c3b-4a4b-83b5-aa2a9ef4c2f6)

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

TrevorBaum commented in Github:

Hi @ezra-latina, thanks for putting this list together with screenshots! Are these all things that need to be addressed before launch? Or did you just want to capture all of these in one place so we have a design backlog for the site? Thanks.

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/762

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

TrevorBaum commented in Github:

Went through the website with @ezra-latina , here's some additional feedback:

**HOME PAGE (LO)**
- Add hover states for Join button, Sign In link (underline?), footer links (could be grey and turn white with hover, similar to footer in the LI HP) 

**Home Page (LI)**
- on second card, "Upload your tracks to make vids in the app" has an orphan. Maybe shorten to just "Upload your tracks!" or add a couple more words so it fills out the two lines better
- Hover state for rainbow Add Track button is a reddish glow - should we use white border instead? 

**Profile/Edit Profile**
- After editing your profile, it displays a small success message with awkward text (as mentioned above). We could potentially reuse the "Link Copied" pattern from the web player, which is more prominent, and change the text to say something more clear like "Profile Updated"
- After editing your profile, it should display the success message and take you back to the Profile screen
- Increase line height or padding slightly between fields/sections of the profile. Right now it's a little cramped


Ezra, feel free to add anything else. I will create a separate ticket for the web player feedback.

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

chihyuC commented in Github:

dup of https://github.com/TRASH-INC/Benny/issues/762
