### ISSUE TITLE
Add /channel/<id> for all channels including user profile channels

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#369]
As a company, we want to be able to share a channel of videos on the web.As a company and as a user, I want to be able to share a channel of my videos (ie. my profile) on the web.

****Acceptance Criteria****

Add `/channel/<id>` that loads a web view for any given `channel_id`

The link should work for any channels including all pre-defined channels, artist channels, and user profile channels... etc

The link should not require any `post_id` like the existing channel player

This ticket is part ofhttps://github.com/TRASH-INC/Grizzy/issues/1389

**Comment by karina4now** [comment]
> Rafał Dzięgielewski commented in Jira:

Regarding the links - I can either make them look like:/player/channel/<channel_id>/player/channel/<channel_id>/post/<post_id>/player/post/<post_id>

or:/player?channelId=<channel_id>&postId=<post_id>

**Comment by karina4now** [comment]
> Chihyu Chang commented in Jira:

Rafał Dzięgielewskiis it hard to drop/player?

**Comment by chihyuC** [comment]
dup of https://app.zenhub.com/workspaces/product-5cb8894efec3b63424e0f4d3/issues/trash-inc/benny/797

**Comment by karina4now** [comment]
> Arkadiusz Pęcherz commented in Jira:

On the example of the profile channel

/player/😛ostIdhttps://development.benny.trash.app/player/245b67df-f48f-483c-b790-638d5d88ced7

/player/post/😛ostIdhttps://development.benny.trash.app/player/post/245b67df-f48f-483c-b790-638d5d88ced7

/player/channel/:channelIdhttps://development.benny.trash.app/player/channel/067f1ed3-ae64-4d8b-a2f1-ed51491210d4/

/player/channel/:channelId/post/😛ostIdhttps://development.benny.trash.app/player/channel/067f1ed3-ae64-4d8b-a2f1-ed51491210d4/post/245b67df-f48f-483c-b790-638d5d88ced7

/player2/😛ostId (redirect should work)https://development.benny.trash.app/player2/245b67df-f48f-483c-b790-638d5d88ced7

/player2/😛ostId?channelId=:channelId (redirect should work)https://development.benny.trash.app/player2/245b67df-f48f-483c-b790-638d5d88ced7?channelId=067f1ed3-ae64-4d8b-a2f1-ed51491210d4
