### ISSUE TITLE
Android wait list for VC

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#374]
As an Android user, I want to sign up because I'm going to be annoyed and disappointed.

**AC:**
* Needs better copy from current - what do we want them to read after hitting a button that says "download the app" and feeling disappointed

* Needs better attention for mobile view (headline is too large)

* Needs some testing on Android. Does it open in Snap browser or in Chrome? (They'll be more likely to go through it if in Chrome bc info is pre-filled).

**Note:** this is a different form than the one we already have which is on our website. We need to track people who come from the two different places.

@chihyuC can we open this in Chrome via branch.io?

**Comment by ezra-latina** [comment]
Form has been created here: https://drive.google.com/open?id=13II2HCWLPuVqHvZP-tD1ikJJq9rvBKPflr9DrsEfamc

it is ready to be connected to branch.io

**Comment by hannahdonovan** [comment]
Reviewed design, signed off.

This needs some testing on Android now.

**Comment by hannahdonovan** [comment]
Got a friend to test this and it works fine. Opens in Chrome unless the user has set their prefs to another browser
