### ISSUE TITLE
Vibe Check website

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#377]
As an anonymous web user, or an android user, I want my own vibe check to share with friends so that I can join.

As a company we wan to increase our reach with this so that we add more users and collect emails.

Related backend tasks (SBs)
Front end (need to ask Eden / Simon)

![vibe check web flow.png](https://images.zenhubusercontent.com/5cba4ff1fec3b63424e0f7d8/e77989ae-4f54-439d-959b-4309e5886c7d)

**Comment by edensg** [comment]
working on this here! https://github.com/TRASH-INC/Benny/pull/927
