### ISSUE TITLE
Black screen when loading snap web views

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#383]
bug reported by @ArmandTrash 

staging.benny.trash

**Comment by chihyuC** [comment]
Sample links:
https://staging.benny.trash.app/vibecheck/3ebc20cc-4ff5-4320-9e0a-f1d4e244d7fb
https://staging.benny.trash.app/vibecheck/59635353-273c-44e2-a346-76a298a5d618


After digging further, this issue will happen to a vibe check that has already expired with 0 vote on it.

@dziraf already had a fix in review for this
