### ISSUE TITLE
Add analytics to web

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#390]
As a company, we need to add Amplitude analytics to the websites so that we are properly tracking information.

**Next steps:**
- [x] Armand to write AC for this
- [x] Figure out resourcing - Chihyu
- [x] Break down acceptance criteria below
- [x] Create new Amplitude projects - Chihyu

**AC**
- Set up and integrate Amplitude (keep existing GTM tracking intact)
- Add basic page visits to all web pages, in the format of `viewed_xxx` (ex. `viewed_webplayer` or `viewed_vibecheck`)
- Add custom events listed below in `Must have` and `  Nice to have soon` sections, examples:
=> `viewed_vibecheck`: VC vote page visit by source
=> `did_vote_vibecheck`: VC vote action by source
=> `did_tap_download`: Clicked on download button
- Link items listed in `Properties` section for each event logged

Events + Metrics   

Must Have :  
- User visited vibe check page [Event Properties: "iOS", "Web", "Android-Web" for where vc is created] (We want this logged as a custom event in amplitude)
- Snapchat VC: Tap/Clicked on Vibe Check Poll [Event Properties: "Pass" or "Fail]  
- Snapchat VC: Tapped to Download(*) 
- VC Android site: Visited Page 
- VC Android site: Tapped "Add to snapchat" (main yellow CTA,  not the text copy is subject to change).  

  Nice to have soon:  
- VC Web site: Page Visit (Vibeche.cc)
- (*)Snapchat VC: Tapped to Download BEFORE voting
- (*)Snapchat VC: Tapped to Download AFTER voting [Event Properties: tapped "Banner" or "Yellow CTA"]
- VC Web site: Voted on Custom vibe check  - VC Web site: Created a vibe check
- VC Web site: clicked vibe check share link 
- VC Web site: clicked "Download TRASH" CTA on Home page

  Nice to have in general:
- VC Web site: Page Visit (Vibeche.cc) 
- VC Web site: Voted on HOME PAGE 
- VC Web site: clicked/tapped "Get your own vibe check" on Custom Vibe Check 
- VC Web site: Clicked Get Your Own Vibe check 
- VC Web site: clicked vibe check share link 
- VC Web site: clicked "Download TRASH" CTA on Home page  
- Web player page: viewed page
- Web player page: played video 
- Web player page: copied link 
- Web player page: tapped open trash 
- Web player page: tapped Trash logo header 
- Web site Home page: Clicked/Tapped Download app store 
- Web site Home page: Clicked/Tapped Trash Mag 
- Web site Home page: Clicked/Tapped "get a vibe check on the web"  

Properties: 
- Device type (os, phone, desktop) 
- Browser type (Safari, Chrome, In-app, etc..)  
- New User 
- Web Version (Is this a thing? If not, I'll use dates and release notes) 

Terms: 
Snapchat VC: These are events that happen on the vibe check voting and results screen, from Vibe checks created on snapchat. These exclude events occurring on vibeche.cc or vibecheck created outside of snapchat.  

VC Web site: events that occur on vibeche.cc, not related to snapchat 

VC Android site: events that occur on Snapkit Creative kit Web page (eg vibeche.cc/android) 

Web site Home page: events that occur on trash.app domain 

Web player page: events on page hosting TRASH video 

- Which Pages the users visited
On Vibeche.cc Desktop 
- Created Vibe check 
- Shared Vibe Check

**Comment by hannahdonovan** [comment]
This looks good, thank you Armand. Feedback:

1. @chihyuC we should figure out how much work this is and may need to prioritize some of these. It could be a lot to implement?

2. We should make sure we have page flow in Amplitude for getting from point A to B to C so we can see where people churn out

**Comment by chihyuC** [comment]
@hannahdonovan in our code base it looks like we already have GTM integrated but I don't seem to have access to it, do you? If it's working, then we should at least have page views (if we're ok using GTM, instead of Amplitude)

Yes it would be time consuming to add all events at once, my suggestion is to prioritize vibe check events, on the most critical flow, maybe Snapchat VC / Android then website specific events?

Analytics on trash.app will need to be tracked/handled separately.

**Comment by hannahdonovan** [comment]
@Katyento to figure out where this goog analytics acct is coming from?

**Comment by Katyento** [comment]
@chihyuC @hannahdonovan Found google analytics under deprecated_ops@trash.app - LMK if this needs further digging.

**Comment by chihyuC** [comment]
@dziraf I've updated the AC for this ticket so it's ready for implementing, note that it's fine to skip items in the `Nice to have in general` section.

Please work with @ArmandTrash to verify events are logged correctly.

**Comment by hannahdonovan** [comment]
FYI didn't do "nice to have in general"
