### ISSUE TITLE
After pressing a "Vi... Check Poll" button user gets an error "Something went wrong. Try again"

### ISSUE THREAD

**Issue by Reactor94** [TRASH-INC/trash-inc.github.io#391]
**Software version:**  12.4.5
**Model:** iPhone 5s
**Environment:** Staging, Dev

**Steps to reproduce** :

1. Click on Start a **Vi...Check Poll** in the Home page

**Actual result:** User gets an error "Something went wrong. Try again" And is not redirected to the Snap chat
**Expected result:** User should be redirected to the Snap chat.

**Note:** This bug occurs randomly. And the same issue is occurring when user tries to login to the app with Snap chat

**Comment by chihyuC** [comment]
Can you confirm if this only occurs on dev, not staging?

In dev, it should fail 100% of time because testing Snapchat in development environment is open to only demo users. If you give me your Snapchat username I can fix it.

In staging, it should just work.

**Comment by Reactor94** [comment]
Yes, it occurs only on dev. 

It is my username - vitalik_pylypet

**Comment by chihyuC** [comment]
Added you. The problem should go away now.
