### ISSUE TITLE
Update website dl  button 12/10

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#404]
Link to "Blog" instead.

**Comment by Katyento** [comment]
Also adding to remove dl link from Trash Mag. Or does that get removed when you remove from trash.app?

![image.png](https://images.zenhubusercontent.com/5ee7ac597a136f4b259f5d5b/5208cfa5-77f9-4eb2-8f8f-eb6706cfa3d6)

**Comment by hannahdonovan** [comment]
Change copy: Download -> Blog
Change link

**Comment by genp** [comment]
Remove from trash.app but not from Mag...
