### ISSUE TITLE
Update FAQ 12/10

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#408]
Go to "code"
Go to "edit"
Copy and paste the entire html from an FAQ entry, and then change the copy to say:

**Why can't I download the Trash App?**
Trash is no longer available on the App Store. If you previously have downloaded the app to your phone, you can still use it until Dec 18, 2020 to download your videos.

Put this Q&A at the top of the "VSCO" section.

Commit it, put it live.
Check to make sure everything looks okay!

**Comment by Katyento** [comment]
Updated. I thought it looked better after the first question but can update it if you feel otherwise. 

![image.png](https://images.zenhubusercontent.com/5ee7ac597a136f4b259f5d5b/6a009843-27fe-48e8-871d-5bad97f1c858)
