### ISSUE TITLE
TFA website homepage

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#47]
As a company, we need to launch TFA with a proper homepage so that we look profesh!

**Notes:**
* This is being designed by Simon for delivery 4/28 to start the next sprint with the SBs
* Han working with Piotr on if this is feasible for them to implement, I hope that can work!
* Needs a quick creative brief re: what should be included in the header, footer, signup / in links, CTA. Simon can help write copy but some starting points would be helpful
* Simon needs the creative brief for next week Mon 4/20

cc @TrevorBaum for the brief

**Comment by piotr-brzeczek-sb** [comment]
https://kmpgroup.atlassian.net/browse/TRSH-208

**Comment by hannahdonovan** [comment]
In development with SBs
