### ISSUE TITLE
Web player for Channels

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#52]
@ezra-latina commented on [Thu Apr 23 2020](https://github.com/TRASH-INC/Grizzy/issues/1478)

**Acceptance criteria and must have scope**
Upgrade current experience:
- Layout should account for horizontal or vertical video within a responsive website
- Video player should have a better affordance for play button, and clean up the player UI in general (second part NTH)
- Update metadata associated with the video based on the preview link copy
- Update call to action to meet our growth key result
- Once support for channels is offered, add link support to the user’s profile (channel) and a “watch more…” link to GOAT.

Support for channels:
- Video player needs to support multiple videos with a next and previous button
- All the things listed in part 1 above
- Potentially a CTA to watch more channels, like a grid of others to explore (NTH)

---

@hannahdonovan commented on [Mon Apr 27 2020](https://github.com/TRASH-INC/Grizzy/issues/1478#issuecomment-620104038)

Update: need design for showing multiple videos in a channel, include channel title

**Comment by piotr-brzeczek-sb** [comment]
https://kmpgroup.atlassian.net/browse/TRSH-268

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

piotr-brzeczek-sb commented in Github:

https://kmpgroup.atlassian.net/browse/TRSH-268

**Comment by karina4now** [comment]
> Karina Bernacki commented in Jira:

karina4now commented in Github:

> Karina Bernacki commented in Jira:

piotr-brzeczek-sb commented in Github:

https://kmpgroup.atlassian.net/browse/TRSH-268
