### ISSUE TITLE
Spinning Halo on Home Page + update icons from rainbow to purple

### ISSUE THREAD

**Issue by ela-trash** [TRASH-INC/trash-inc.github.io#8]
Replace current halo with spinning halo:

https://drive.google.com/drive/u/1/search?q=spinning%20halo

If needed in different dimensions/file sizes pls lmk :)

Also update social icons from rainbow to purple (same color as text).

**Comment by juweek** [comment]
Hey, can you upload the link again? Can't access using the one you posted

**Comment by ela-trash** [comment]
hi, try this:

https://drive.google.com/a/trash.app/file/d/10LRQsFYSPKSj1HSaXn4H_PVFOup1c0Xi/view?usp=sharing

I have also linked it on the brief for the website, but if neither of those work lmk!

**Comment by lujainibrahim** [comment]
resolved!
