### ISSUE TITLE
As a User, I want to sign up with my Snapchat account

### ISSUE THREAD

**Issue by karina4now** [TRASH-INC/trash-inc.github.io#90]
**Acceptance criteria**

User can be registered using existing Snapchat account

**Comment by karina4now** [comment]
> Chihyu Chang commented in Jira:

Rafał DzięgielewskiI had a chance to look into this API and made some changes before (and broke the test… !!!)

So just to add a bit more context. The auth flow in the iOS app looks like this

We call Firebase to create or log in an user and obtain the Firebase token

We call/v1/authenticatewith the Firebase token to create or log in a user

In the case for Snap auth, we rely on server to handle the first step and return a Firebase custom token.

The error I encountered was that, while rarely, the second step could fail. When this happens, Firebase already have a user record with the associated Snap user id, but it didn’t exist in our DB. Currently we simply threw an error and there’s nothing the user can do, unless they contact us, then we go ahead and remove that user record from Firebase.

Ideally, I’d love that we could have server handle this error gracefully with going through user support, either

Remove the user record and re-create a new one (just like what we would do manually), and the return the custom token

Simply retrieve the custom token if existing user record, if possible, and return it

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/568
